#!/usr/bin/env bash
# Setup coturn on Ubuntu 22.04+ with certbot TLS and a shared secret for ephemeral credentials.
# Usage: sudo ./scripts/setup_coturn.sh example.com SHARED_SECRET
# Or set environment variables: DOMAIN and SHARED_SECRET

set -euo pipefail

DOMAIN=${1:-${DOMAIN:-}}
SHARED_SECRET=${2:-${SHARED_SECRET:-}}

if [[ -z "$DOMAIN" || -z "$SHARED_SECRET" ]]; then
  echo "Usage: sudo $0 <turn-domain> <shared-secret>"
  echo "Example: sudo $0 turn.example.com $(openssl rand -base64 18)"
  exit 2
fi

echo "Setting up coturn for domain: $DOMAIN"

# Update and install
apt-get update
apt-get install -y coturn certbot ufw

# Obtain TLS cert using certbot (standalone). This will temporarily bind to port 80.
echo "Obtaining TLS certificate for $DOMAIN using certbot (standalone)."
certbot certonly --non-interactive --agree-tos --register-unsafely-without-email --standalone -d "$DOMAIN" || {
  echo "certbot failed. You may need to run certbot interactively or ensure port 80 is free.";
}

CERT_DIR="/etc/letsencrypt/live/$DOMAIN"
FULLCHAIN="$CERT_DIR/fullchain.pem"
PRIVKEY="$CERT_DIR/privkey.pem"

if [[ ! -f "$FULLCHAIN" || ! -f "$PRIVKEY" ]]; then
  echo "Certificate not found at $FULLCHAIN or $PRIVKEY. Please check certbot output.";
fi

# Create coturn config include
INCLUDE_DIR="/etc/turnserver.conf.d"
mkdir -p "$INCLUDE_DIR"
CONF_FILE="$INCLUDE_DIR/00-coturn.conf"

cat > "$CONF_FILE" <<EOF
# Automatically generated by scripts/setup_coturn.sh
listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=$SHARED_SECRET
realm=$DOMAIN
cert=$FULLCHAIN
pkey=$PRIVKEY
min-port=49152
max-port=65535
# Uncomment and set relay-ip / external-ip if NATting
#relay-ip=YOUR_DROPLET_IP
#external-ip=YOUR_PUBLIC_IP
EOF

# Ensure turnserver is enabled in default config
if grep -q "^#TURNSERVER_ENABLED=1" /etc/default/coturn 2>/dev/null; then
  sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn
else
  # add if missing
  echo "TURNSERVER_ENABLED=1" >> /etc/default/coturn
fi

systemctl enable coturn
systemctl restart coturn || true

# Setup UFW rules (non-destructive)
ufw allow OpenSSH || true
ufw allow 3478/tcp || true
ufw allow 3478/udp || true
ufw allow 5349/tcp || true
ufw allow 5349/udp || true
ufw allow 49152:65535/udp || true

if ufw status | grep -q inactive; then
  echo "Enabling UFW (firewall)."
  ufw --force enable
fi

cat <<EOT

Setup complete (attempted).
- Coturn service: systemctl status coturn
- Certs: $FULLCHAIN and $PRIVKEY
- Shared secret set in $CONF_FILE (static-auth-secret)

Next manual steps you may want to perform:
- If your droplet is behind NAT, edit $CONF_FILE and set relay-ip and external-ip.
- Verify coturn logs: journalctl -u coturn -f
- If certbot failed earlier, run: sudo certbot certonly --standalone -d $DOMAIN

Security note:
- Keep $SHARED_SECRET safe. Add it to your Render/Vercel secrets as TURN_SHARED_SECRET.

EOT
